#Generated once for configuration of goals
#Config config/MoveBaseDeliver_goal.yaml
target_pose:
  header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: '/map'
  pose:
    position:
      x: 3.402
      y: 0.404
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -0.129
      w: 0.992
      
